In [100]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [101]:
cd D:\MAESTRIA ANALITICA UCENTRAL\Bases de datos\Guatemala

D:\MAESTRIA ANALITICA UCENTRAL\Bases de datos\Guatemala

In [23]:
ls

 El volumen de la unidad D es Datos
 El número de serie del volumen es: 36C6-66E7

 Directorio de D:\MAESTRIA ANALITICA UCENTRAL\Bases de datos\Guatemala

03/11/2022  05:25 p. m.    <DIR>          .
03/11/2022  05:25 p. m.    <DIR>          ..
03/11/2022  04:06 p. m.           270.387 1  censo .xlsx
03/11/2022  05:25 p. m.           267.270 censo.xlsx
02/11/2022  08:55 p. m.    <DIR>          empleoeingresos
03/11/2022  04:07 p. m.        11.644.781 empleoeingresos (1).zip
02/11/2022  08:53 p. m.               538 empleoeingresos.zip
02/11/2022  08:52 p. m.         1.045.195 Guatemala_BM_V2.xlsx
02/11/2022  08:53 p. m.           100.130 guatemala_cos_fy19_eng_final.csv
02/11/2022  08:54 p. m.           528.492 guatemala_cos_fy19_eng_final_.pdf
02/11/2022  08:54 p. m.           344.017 investigadores_2021 .xlsx
               8 archivos     14.200.810 bytes
               3 dirs  847.134.400.512 bytes libres

In [117]:
#dfx = pd.read_csv('examen3.csv', sep=';', encoding='utf-8')
dfx = pd.read_excel('censo.xlsx', index_col=0)
dfx1 = pd.read_csv('censo_Limpieza1.csv', sep=';', encoding='utf-8')
dfe = pd.DataFrame(dfx)
dfe = dfe.reset_index()
dfe1 = pd.DataFrame(dfx1)
dfe1 = dfe1.reset_index()

In [25]:
def mayor(datos):
    '''
    Función mayor
    Toma cada una de las variables que se encuentran en el base, para realizar el contéo de las veces que aparece, así generar la frecuencia y seleccionar
    el valor de mayor frecuencia
    repeticiones: espacio donde se guardará el listado de las frecuencias por cada uno de los valores.
    '''
    y=datos.dropna()
    repeticiones = 0
    x=[]
    rep=[]
    for i in y:
        x.append(str(i))
    for i in x:
        n = x.count(i)
        if n > repeticiones:
            repeticiones = n
            rep.append(repeticiones)
    return(max(rep))

In [26]:
def moda(datos):
    '''
    Función moda
    Toma cada una de las variables que se encuentran en el base, para realizar el cálculo de la moda
    moda: espacio donde se guardará el listado de los valores de mayor frecuencia para cada variable.
    n: espacio donde queda la cantidad de veces que aparece cada elemento de la lista
    '''
    repeticiones = 0
    y=datos.dropna()
    x=[]
    for j in y:
        x.append(str(j))
    for j in x:
        n = x.count(j)
        if n > repeticiones:
            repeticiones = n

    sali = [] #Arreglo donde se guardara el o los valores de mayor frecuencia 

    for j in x:
        n = x.count(j) # Devuelve el número de veces que x aparece enla lista.
        if n == repeticiones and j not in sali:
            sali.append(j)
    return(sali)

In [27]:
def atributos_data(x):
  '''
  Función atributos_data
  Toma cada una de las variables que se encuentran en el base, para crear un data frame en el cual cada fila corresponde a cada una de las variables
  existentes en la base y cada columna corresponde a cada uno de los siguintes cálculos:
  - Nombre de la columna
  - Tipo de dato de la columna (incluido: int, float, string, datetime, boolean, object)
  - Tipo de la variable (continua, numérica discreta, categórica)
  - Cantidad de valores nulos
  - Valor que más se repite
  - Frecuencia del valor que más se repite
  - Valor máximo (este cálculo aplica unicamente para variables de tipo "int" y "float")
  - Valor mínimo (este cálculo aplica unicamente para variables de tipo "int" y "float")
  '''
  columnas = x.columns.to_list()
  nombre=[]
  tipo_dato=[]
  tipo_variable=[]
  valores_unicos=[]
  valores_nulos=[]
  Mayor_frecuencia=[]
  frecuencia=[]
  Maximo=[]
  Minimo=[]
  raiz=[]
  for i in columnas:
    nombre.append(i)
    if x[i].dtype == 'O':
      dato = 'string'
      variable = 'categórica'
    elif x[i].dtype == 'int64':
      dato = 'int'
      variable = 'discreta'
    elif x[i].dtype == 'float64':
      dato = 'float'
      variable = 'continua'
    elif x[i].dtype == 'datetime64[ns]':
      dato = 'datetime'
      variable = 'categórica (date)'  
    tipo_dato.append(dato)
    tipo_variable.append(variable)
    valores_unicos.append(len(x[i].unique()))
    valores_nulos.append(x[i].isnull().sum())
    Mayor_frecuencia.append(moda(x[i]))
    frecuencia.append(mayor(x[i]))
    y=x[i].dropna()
    if x[i].dtype == 'O':
          Maximo.append("N/A")
    elif x[i].dtype == 'datetime64[ns]':
          Maximo.append("N/A")
    elif x[i].dtype == 'int64':
        Maximo.append(str(max(y)))
    elif x[i].dtype == 'float64':
        Maximo.append(str(max(y)))
    if x[i].dtype == 'O':
          Minimo.append("N/A")
    elif x[i].dtype == 'datetime64[ns]':
          Minimo.append("N/A")
    elif x[i].dtype == 'int64':
        Minimo.append(str(min(y)))
    elif x[i].dtype == 'float64':
        Minimo.append(str(min(y)))
    raiz.append(round(len(x[i])**0.5, 2) > len(x[i].unique()))
  atributos = pd.DataFrame({'Nombre_Columna': nombre, 'Tipo de dato': tipo_dato, 'Tipo de Variable': tipo_variable,
                            'Valores únicos': valores_unicos, 'Valores nulos': valores_nulos, 'dato frecuente': Mayor_frecuencia,
                            'Total dato frec.': frecuencia, 'Valor máximo': Maximo, 'Valor mínimo': Minimo})
  return atributos

In [104]:
atributos_data(dfe1)

,Nombre_Columna,Tipo de dato,Tipo de Variable,Valores únicos,Valores nulos,dato frecuente,Total dato frec.,Valor máximo,Valor mínimo
0,index,int,discreta,1174,0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",1,1173,0
1,Area Doctorado Actual Especifica,string,categórica,23,916,"[ Antropología y etnología, demografía, geogra...",46,N/A,N/A
2,Area Estudio Maestria Especifica,string,categórica,24,0,[Otro],260,N/A,N/A
3,Area Estudio Postdoctorado Especifica,string,categórica,14,1143,"[ Ciencias biológicas (biología, botánica, bac...",7,N/A,N/A
4,Area Laboral,string,categórica,905,0,[Docencia],31,N/A,N/A
5,Area Laboral grupo,string,categórica,564,0,[Investigacion],97,N/A,N/A
6,Codigo Departamento,int,discreta,22,0,[1],809,22,1
7,Codigo Pais Residencia,float,continua,36,7,[1.0],1020,186.0,1.0
8,Entidad Laboral,string,categórica,867,0,[Universidad de San Carlos de Guatemala],51,N/A,N/A
9,Estatus,string,categórica,2,0,[Titulo de maestría],1001,N/A,N/A
10,Estatus Doctorado,string,categórica,3,1038,[Estudiante de doctorado],73,N/A,N/A
11,Estatus Posdoc,string,categórica,3,1143,[Postdoctorado],21,N/A,N/A
12,Genero,string,categórica,2,0,[Hombre],588,N/A,N/A
13,Id,string,categórica,1153,0,"[26c44af2db5c6844c0f9aa472ec9aef8, 7714b37395b...",3,N/A,N/A
14,Institucion Doctorado,string,categórica,197,916,[Universidad Galileo],10,N/A,N/A
15,Institucion Doctorado grupo,string,categórica,180,916,"[Universidad Galileo,Universidad Galileo - Ins...",14,N/A,N/A
16,Institucion Maestria,string,categórica,548,2,[Universidad Galileo],83,N/A,N/A
17,Institucion Maestria grupo,string,categórica,453,2,[Universidad de San Carlos],106,N/A,N/A
18,Institucion Postdoctorado,string,categórica,32,1143,"[Universidad Maimónides/Fundación Aiglé,, Mich...",1,N/A,N/A
19,Institucion Postdoctorado grupo,string,categórica,32,1143,"[Universidad Maimónides/Fundación Aiglé,, Mich...",1,N/A,N/A
20,Labora Actualmente,string,categórica,2,0,[Sí],997,N/A,N/A
21,Lugar Nacimiento,string,categórica,138,0,[Guatemala],756,N/A,N/A
22,Nombre Doctorado,string,categórica,227,916,[Doctorado en Educación],5,N/A,N/A
23,Nombre Master Actual,string,categórica,1015,2,[MBA],23,N/A,N/A
24,Sector Pertenece,string,categórica,3,0,[Privado],526,N/A,N/A
25,Titulo Postdoctorado,string,categórica,30,1143,[No Aplica],3,N/A,N/A
26,Titulo Pregrado,string,categórica,720,0,[Ingeniero Agrónomo],30,N/A,N/A
27,Universidad Pregrado,string,categórica,292,0,[Universidad de San Carlos de Guatemala],238,N/A,N/A
28,Year Doctorado,float,continua,29,916,[2018.0],46,2025.0,1017.0
29,Year Master,int,discreta,51,0,[2017],174,9999,1
30,Year Nacimiento,int,discreta,56,0,[1986],70,2017,41
31,Year Postdoc,float,continua,15,1143,[2017.0],6,2020.0,1976.0
32,Year Pregrado,int,discreta,51,0,[2012],93,2019,71
33,Area Doctorado Actual,float,continua,7,940,[5.0],95,6.0,1.0
34,Area Estudio Maestria,float,continua,7,260,[5.0],415,6.0,1.0
35,Area Estudio Postdoctorado,float,continua,6,1143,[1.0],18,6.0,1.0

In [15]:
dplan = dfe

In [ ]:
def datos_ajustados(x):

    '''
  Función datos_ajustados
  Esta función tienen como finalidad arreglar las variables que tienen problemas con caracteres especiales y que su formato no es el correcto.
  x = es la base de datos o Dataframe
  Se utilizan dos comandos de pandas:
  pd.to_numeric = para la transformación de las variables a tipo numéricas (int o float)
  pd.to_datetime = para la transformación de las variables a tipo datatime (datatime)
  '''
    x.lugar_nacimiento = x.lugar_nacimiento.upper()
    

    return(x)

In [90]:
#lugar_nacimiento = dfe['lugar_nacimiento']
dfe.lugar_nacimiento = dfe.lugar_nacimiento.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.estatus = dfe.estatus.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.universidad_pregrado = dfe.universidad_pregrado.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.estatus = dfe.estatus.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.nombre_master_actual = dfe.nombre_master_actual.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.institucion_maestria = dfe.institucion_maestria.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.area_estudio_maestria_especifica = dfe.area_estudio_maestria_especifica.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.institucion_doctorado = dfe.institucion_doctorado.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.area_doctorado_actual_especifica = dfe.area_doctorado_actual_especifica.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.titulo_postdoctorado = dfe.titulo_postdoctorado.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('E', 'É').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.institucion_postdoctorado = dfe.institucion_postdoctorado.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.labora_actualmente = dfe.labora_actualmente.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.entidad_laboral = dfe.entidad_laboral.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.sector_pertenece = dfe.sector_pertenece.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe.area_laboral = dfe.area_laboral.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
#dfe.titulo_postdoctorado.str.upper()
#dfe.institucion_postdoctorado.str.upper()
#dfe.area_estudio_postdoctorado_especifica.str.upper()
#dfe.labora_actualmente.str.upper()

In [116]:
dfe

,id,lugar_nacimiento,codigo_departamento,year_nacimiento,codigo_pais_residencia,genero,titulo_pregrado,universidad_pregrado,year_pregrado,estatus,...,estatus_posdoc,titulo_postdoctorado,institucion_postdoctorado,area_estudio_postdoctorado,area_estudio_postdoctorado_especifica,year_postdoc,labora_actualmente,entidad_laboral,sector_pertenece,area_laboral
0,1e1dabd09f905cf432dda610211d21a9,Pajapita,16,1977,1.0,Hombre,Magister en Negocios Electrónico,Universidad Galileo,2008,Titulo de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,Universidad Galileo,Académico,Director de carrera
1,ab482ae86aabc77c8b0807abd0fafdb3,Mazatenango,10,1956,1.0,Hombre,Abogado,USAC,1998,Titulo de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,LEGIS y USAC,Académico,Docencia y consultoría
2,25a797e2ceca844873e00c0792d86d36,Mazatenango,10,1976,1.0,Hombre,Ingeniero Agrónomo,Universidad de San Carlos de Guatemala,2001,Titulo de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,Escuela Regional de Ingeniería Sanitaria y Rec...,Académico,Docencia
3,8322ae047987c2b251263888553d5a77,"Buenos Aires, Argentina",1,1955,1.0,Mujer,Licenciatura en Ciencias de la Información,Universidad Nacional de La Plata,1977,Titulo de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,Consultora PNL NEGOCIOS Univesidad Galileo Age...,Privado,"consultora en innovación, gestión de conocimie..."
4,fc10728e0b84a325b418db1b2e35c935,Retalhuleu,11,1962,1.0,Hombre,Químico Biólogo,Universidad de San Carlos de Guatemala,1989,Titulo de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,Universidad de San Carlos de Guatemala,Académico,Cooperación Internacional
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1169,ad207966e0fb4a599eac051ddff4f544,Villa Nueva,1,1985,1.0,Mujer,Química Farmacéutica,USAC,2010,Estudiante de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,MSPAS,Público,Logistica de Medicamentos
1170,79083c274a8882f863060a34cad15b65,Zacapa,19,1954,1.0,Hombre,Licenciatura en Zootecnia,"Facultad de Medicina Veterinaria y Zootecnia, ...",1982,Titulo de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,"Facultad de Medicina Veterinaria y Zootecnia, ...",Académico,"Coordinación de la Unidad de Vinculación, FMVZ..."
1171,1802620bb9949635d3e0fcf3c46bf911,Zacapa,19,1984,63.0,Hombre,Médico y Cirujano en grado de Licenciado,Universidad Francisco Marroquin,2010,Titulo de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,Hospital Universitario de Gran Canaria Dr Negrin,Público,Oncologia Radioterapica
1172,ae348e850accd270e85df63b259a766e,Zacualpa,14,1968,1.0,Hombre,Ingeniero Ambiental,Universidad Rural de Guatemala,2007,Titulo de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,USAID-AGEXPORT,Privado,AGROAMBIENTAL
1173,ad99b594d2fe86a35dd9b023f554175c,Zaragoza,4,1988,1.0,Hombre,Medico veterinario,USAC,2013,Estudiante de maestría,...,NaN,NaN,NaN,NaN,NaN,NaN,Sí,World Horse Welfare,Público,Rural

In [120]:
dfe1.Area_Doctorado_Actual_Especifica

0                                Ciencias de la educación
1        Antropología y etnología, demografía, geograf...
2                                                     NaN
3        Antropología y etnología, demografía, geograf...
4                                                     NaN
                              ...
1169                                                  NaN
1170                                                  NaN
1171                                                  NaN
1172                                                  NaN
1173                                                  NaN
Name: Area_Doctorado_Actual_Especifica, Length: 1174, dtype: object

In [138]:
#PARA DATASET LIMPIO
dfe1.Lugar_Nacimiento = dfe1.Lugar_Nacimiento.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Estatus = dfe1.Estatus.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Universidad_Pregrado = dfe1.Universidad_Pregrado.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
#dfe1.estatus = dfe1.estatus.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Nombre_Master_Actual = dfe1.Nombre_Master_Actual.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Institucion_Maestria = dfe1.Institucion_Maestria.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Area_Estudio_Maestria_Especifica = dfe1.Area_Estudio_Maestria_Especifica.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Institucion_Doctorado = dfe1.Institucion_Doctorado.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Area_Doctorado_Actual_Especifica = dfe1.Area_Doctorado_Actual_Especifica.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Titulo_Postdoctorado = dfe1.Titulo_Postdoctorado.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('E', 'É').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Institucion_Postdoctorado = dfe1.Institucion_Postdoctorado.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Labora_Actualmente = dfe1.Labora_Actualmente.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Entidad_Laboral = dfe1.Entidad_Laboral.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Sector_Pertenece = dfe1.Sector_Pertenece.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Area_Laboral = dfe1.Area_Laboral.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')


dfe1.Area_Doctorado_Actual_Especifica = dfe1.Area_Doctorado_Actual_Especifica.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Area_Laboral_grupo = dfe1.Area_Laboral_grupo.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Institucion_Doctorado_grupo = dfe1.Institucion_Doctorado_grupo.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Institucion_Maestria_grupo = dfe1.Institucion_Maestria_grupo.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')
dfe1.Institucion_Postdoctorado_grupo = dfe1.Institucion_Postdoctorado_grupo.str.upper().str.replace('Í', 'I').str.replace('Á', 'A').str.replace('É', 'E').str.replace('Ó', 'O').str.replace('Ú', 'U')


#dfe1.Area_Doctorado_Actual_Especifica
#dfe1.Area_Laboral_grupo
#dfe1.Institucion_Doctorado_grupo
#dfe1.Institucion_Maestria_grupo
#dfe1.Institucion_Postdoctorado_grupo

In [139]:
dfe = dfe.drop_duplicates()
dfe1 = dfe1.drop_duplicates()

In [143]:
dfe1.to_excel("censo_pos_python.xlsx")

In [92]:
dfe.area_laboral.groupby

<bound method Series.groupby of 0                                     DIRECTOR DE CARRERA
1                                  DOCENCIA Y CONSULTORIA
2                                                DOCENCIA
3       CONSULTORA EN INNOVACION, GESTION DE CONOCIMIE...
4                               COOPERACION INTERNACIONAL
                              ...
1169                           LOGISTICA DE MEDICAMENTOS
1170    COORDINACION DE LA UNIDAD DE VINCULACION, FMVZ...
1171                              ONCOLOGIA RADIOTERAPICA
1172                                        AGROAMBIENTAL
1173                                                RURAL
Name: area_laboral, Length: 1174, dtype: object>